openapi: 3.0.0
info:
  title: FlexiLease Autos 游뚶
  description: API REST completa para uma locadora de carros
  contact:
    name: Maria Eduarda de S치
    email: desmariaeduarda@hotmail.com
  version: '1.0'
servers:
  - url: http://127.0.0.1:3000/api
paths:
  /car:
    get:
      summary: 'Este endpoint retorna uma lista contendo todos os carros cadastrados.'
      description: 'Este endpoint retorna **todos** os carros cadastrados.'
      tags:
        - Car
      responses:
        '200':
          description: Uma lista de carros.
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/carResponseGet'
    post:
      summary: 'Este endpoint insere um carro no sistema'
      description: 'Este endpoint insere um novo carro no sistema.'
      tags:
        - Car
      requestBody:
        description: Formato JSON que o carro dever치 ser enviado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/carInput'
      responses:
        '200':
          description: Retorna o carro inserido.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/carResponse'
        '500':
          description: Retorna um erro interno no servidor.
  /car/{id}:
    get:
      summary: 'Este endpoint retorna um carro espec칤fico'
      description: 'Este endpoint retorna o carro correspondente ao c칩digo especificado como par칙metro na URL.'
      tags:
        - Car
      parameters:
        - name: 'id'
          in: path
          description: ID do carro que deseja pesquisar.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Retorna o carro especificado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/carResponseGet'
    put:
      summary: 'Este endpoint atualiza um carro no sistema'
      description: 'Este endpoint atualiza um carro no sistema.'
      tags:
        - Car
      parameters:
        - name: 'id'
          in: path
          description: ID do carro que ser치 atualizado.
          required: true
          schema:
            type: integer
      requestBody:
        description: Formato JSON que o carro dever치 ser enviado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/carInput'
      responses:
        '200':
          description: Retorna o carro atualizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/carResponse'
        '500':
          description: Retorna um erro interno no servidor.
    delete:
      summary: 'Este endpoint remove um carro do sistema'
      description: 'Este endpoint remove um carro no sistema.'
      tags:
        - Car
      parameters:
        - name: 'id'
          in: path
          description: ID do carro que ser치 removido.
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Confirma a remo칞칚o com sucesso.
    patch:
      summary: 'Este endpoint edita um acess칩rio de um carro espec칤fico (adi칞칚o ou remo칞칚o)'
      description: 'Este endpoint edita ou remove um acess칩rio de um carro espec칤fico, identificado pelo ID do carro.'
      tags:
        - Car
      parameters:
        - name: 'id'
          in: path
          description: ID do carro cujo acess칩rio ser치 editado ou removido.
          required: true
          schema:
            type: integer
      requestBody:
        description: Nome do acess칩rio que ser치 editado ou removido.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Accessory'
      responses:
        '200':
          description: Retorna o carro atualizado com o acess칩rio modificado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/carResponse'
        '500':
          description: 'Erro interno no servidor.'

  /user:
    post:
      summary: 'Este endpoint insere um usu치rio no sistema'
      description: 'Este endpoint insere um novo usu치rio no sistema.'
      tags:
        - User
      requestBody:
        description: Formato JSON que o usu치rio dever치 ser enviado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userInput'
      responses:
        '200':
          description: Retorna o usu치rio inserido.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
        '500':
          description: Retorna um erro interno no servidor.
  /user/{id}:
    put:
      summary: 'Este endpoint atualiza um usu치rio no sistema'
      description: 'Este endpoint atualiza um usu치rio autenticado no sistema.'
      tags:
        - User
      parameters:
        - name: id 
          description: C칩digo identificador do usu치rio.
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Formato JSON que o usu치rio dever치 ser enviado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userInput'
      responses:
        '200':
          description: Retorna o usu치rio atualizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
        '500':
          description: Retorna um erro interno no servidor.
    get:
      summary: 'Este endpoint retorna um usu치rio espec칤fico'
      description: 'Este endpoint retorna o usu치rio correspondente ao c칩digo especificado na URL.'
      tags:
        - User
      parameters:
        - name: 'id'
          in: path
          description: ID do usu치rio que deseja pesquisar.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Retorna o usu치rio especificado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponseGet'
    delete:
      summary: 'Este endpoint remove um usu치rio do sistema'
      description: 'Este endpoint remove um usu치rio autenticado no sistema.'
      tags:
        - User
      parameters:
        - name: id 
          description: C칩digo identificador do usu치rio.
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Confirma a remo칞칚o com sucesso.

  /auth:
    post:
      summary: 'Este endpoint autentica um usu치rio no sistema'
      description: 'Este endpoint autentica um usu치rio no sistema.'
      tags:
        - User Authentication
      requestBody:
        description: Formato JSON que o usu치rio dever치 enviar para autentica칞칚o.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authInput'
      responses:
        '200':
          description: Retorna o usu치rio autenticado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
        '500':
          description: Retorna um erro interno no servidor.
  
  /reserve:
    post:
      summary: 'Este endpoint insere uma nova resrva no sistema'
      description: 'Este endpoint insere uma nova reserva no sistema.'
      tags:
        - Reserve
      requestBody:
        description: Formato JSON que a rserva dever치 ser enviado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reserveInput'
      responses:
        '200':
          description: Retorna a reserva inserido.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reserveResponse'
        '500':
          description: Retorna um erro interno no servidor.
    get:
      summary: 'Este endpoint retorna uma lista contendo todas reservas cadastradas.'
      description: 'Este endpoint retorna **todas** as reservas cadastradas.'
      tags:
        - Reserve
      responses:
        '200':
          description: Uma lista de reservas.
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/reserveResponseGet'
  /reserve/{id}:
    put:
      summary: 'Este endpoint atualiza uma reservas no sistema'
      description: 'Este endpoint atualiza uma reserva de um usu치rio autenticado no sistema.'
      tags:
        - Reserve
      parameters:
        - name: id 
          description: C칩digo identificador da reserva.
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Formato JSON que a reserva dever치 ser enviado.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reserveInput'
      responses:
        '200':
          description: Retorna a reserva atualizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reserveResponse'
        '500':
          description: Retorna um erro interno no servidor.
    get:
      summary: 'Este endpoint retorna uma reserva espec칤fica'
      description: 'Este endpoint retorna a reserva correspondente ao c칩digo especificado na URL.'
      tags:
        - Reserve
      parameters:
        - name: 'id'
          in: path
          description: ID da reserva que deseja pesquisar.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Retorna a reserva especificada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reserveResponseGet'
    delete:
      summary: 'Este endpoint remove uma reserva do sistema'
      description: 'Este endpoint remove uma reserva de um usu치rio autenticado no sistema.'
      tags:
        - Reserve
      parameters:
        - name: id 
          description: C칩digo identificador da reserva.
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Confirma a remo칞칚o com sucesso.













components:
  schemas:
    carResponse:
      type: object
      properties:
        id:
          type: integer
          description: C칩digo identificador de carro definido automaticamente pelo SGBD.
        model:
          type: string
          description: Modelo do carro.
        color:
          type: string
          description: Cor do carro.
        year:
          type: integer
          description: Ano do carro.
        valuePerDay:
          type: integer
          description: Valor por dia do carro.
        acessories:
          type: array
          description: Lista de acess칩rios do carro.
          items:
            $ref: '#/components/schemas/Accessory'
        numberOfPassengers:
          type: integer
          description: N칰mero de passageiros do carro.
    carResponseGet:
      type: object
      properties:
        id:
          type: integer
          description: C칩digo identificador de carro definido automaticamente pelo SGBD.
        model:
          type: string
          description: Modelo do carro.
        color:
          type: string
          description: Cor do carro.
        year:
          type: integer
          description: Ano do carro.
        valuePerDay:
          type: integer
          description: Valor por dia do carro.
        acessories:
          type: array
          description: Lista de acess칩rios do carro.
          items:
            $ref: '#/components/schemas/Accessory'
        numberOfPassengers:
          type: integer
          description: N칰mero de passageiros do carro.
    carInput:
      type: object
      properties:
        model:
          type: string
          description: Modelo do carro.
        color:
          type: string
          description: Cor do carro.
        year:
          type: integer
          description: Ano do carro.
        valuePerDay:
          type: integer
          description: Valor por dia do carro.
        acessories:
          type: array
          description: Lista de acess칩rios do carro.
          items:
            $ref: '#/components/schemas/Accessory'
        numberOfPassengers:
          type: integer
          description: N칰mero de passageiros do carro.
    Accessory:
      type: object
      properties:
        name:
          type: string
          description: Nome do acess칩rio.
    userInput:
      type: object
      properties:
        name:
          type: string
          description: Nome do usu치rio.
        cpf:
          type: string
          description: Cpf do usu치rio.
        birth:
          type: string
          description: Anivers치rio do usu치rio.
        cep:
          type: integer
          description: Cep do usu치rio.
        email:
          type: string
          description: Email do usu치rio.
        password:
          type: string
          description: Senha do usu치rio.
    userResponse:
      type: object
      properties:
        id:
          type: integer
          description: C칩digo identificador de usu치rio definido automaticamente pelo SGBD.
        name:
          type: string
          description: Nome do usu치rio.
        cpf:
          type: string
          description: Cpf do usu치rio.
        birth:
          type: string
          description: Anivers치rio do usu치rio.
        cep:
          type: integer
          description: Cep do usu치rio.
        email:
          type: string
          description: Email do usu치rio.
        qualified:
          type: boolean
          description: Usu치rio maior de 18 anos.
        neighbordhood:
          type: string
          description: Endere칞o via cep.
        street:
          type: string
          description: Endere칞o via cep.
        complement:
          type: string
          description: Endere칞o via cep.
        city:
          type: string
          description: Endere칞o via cep.
        uf:
          type: string
          description: Endere칞o via cep.
    userResponseGet:
      type: object
      properties:
        id:
          type: integer
          description: C칩digo identificador de usu치rio definido automaticamente pelo SGBD.
        name:
          type: string
          description: Nome do usu치rio.
        cpf:
          type: string
          description: Cpf do usu치rio.
        birth:
          type: string
          description: Anivers치rio do usu치rio.
        cep:
          type: integer
          description: Cep do usu치rio.
        email:
          type: string
          description: Email do usu치rio.
        password:
          type: string
          description: Senha do usu치rio.
    authInput:
      type: object
      properties:
        email:
          type: string
          description: Email do usu치rio.
        password:
          type: string
          description: Senha do usu치rio.
    authResponse:
      type: object
      properties:
        token:
          type: string
          description: Token JWT do usu치rio.
    reserveInput:
      type: object
      properties:
        startDate:
          type: string
          description: Data inicial da reserva.
        endDate:
          type: string
          description: Data final da reserva.
        carId:
          type: integer
          description: id do carro.
    reserveResponse:
      type: object
      properties:
        id:
          type: integer
          description: C칩digo identificador da rserva definido automaticamente pelo SGBD.
        startDate:
          type: string
          description: Data inicial da reserva.
        endDate:
          type: string
          description: Data final da reserva.
        finalValue:
          type: integer
          description: Valor final da reserva.
        userId:
          type: integer
          description: id do usu치rio autenticado.
        carId:
          type: integer
          description: id do carro.
    reserveResponseGet:
      type: object
      properties:
        id:
          type: integer
          description: C칩digo identificador da rserva definido automaticamente pelo SGBD.
        startDate:
          type: string
          description: Data inicial da reserva.
        endDate:
          type: string
          description: Data final da reserva.
        finalValue:
          type: integer
          description: Valor final da reserva.
        userId:
          type: integer
          description: id do usu치rio autenticado.
        carId:
          type: integer
          description: id do carro.
        